// carsData.js
export const cars = [
  {
    id: 1,
    main_image: "/images/cars/toyota-corolla.jpg",
    name: "Toyota Corolla",
    version: "1.6 Hybrid",
    rental_price: 1200,
    deposit_price: 5000,
    description:
      "An economical hybrid with low fuel consumption. Ideal for city driving.",
    created_at: "15.05.2025",
    updated_at: "20.05.2025",
  },
  {
    id: 2,
    main_image: "/images/cars/skoda-octavia.jpg",
    name: "Skoda Octavia",
    version: "1.4 TSI",
    rental_price: 1400,
    deposit_price: 6000,
    description:
      "Spacious interior and comfortable suspension. An excellent choice for work.",
    created_at: "10.05.2025",
    updated_at: "18.05.2025",
  },
  {
    id: 3,
    main_image: "/images/cars/volkswagen-golf.jpg",
    name: "Volkswagen Golf",
    version: "1.5 TSI",
    rental_price: 1300,
    deposit_price: 5500,
    description: "A reliable German car with excellent dynamics.",
    created_at: "12.05.2025",
    updated_at: "19.05.2025",
  },
  {
    id: 4,
    main_image: "/images/cars/bmw-x5.jpg",
    name: "BMW X5",
    version: "xDrive40i",
    rental_price: 2500,
    deposit_price: 10000,
    description: "Luxury SUV with powerful performance and advanced features.",
    created_at: "01.06.2025",
    updated_at: "10.06.2025",
  },
  {
    id: 5,
    main_image: "/images/cars/tesla-model-s.jpg",
    name: "Tesla Model S",
    version: "Plaid",
    rental_price: 3000,
    deposit_price: 12000,
    description:
      "Cutting-edge electric vehicle with unmatched acceleration and range.",
    created_at: "05.06.2025",
    updated_at: "15.06.2025",
  },
  {
    id: 6,
    main_image: "/images/cars/mercedes-e-class.jpg",
    name: "Mercedes-Benz E-Class",
    version: "E 450 4MATIC",
    rental_price: 2800,
    deposit_price: 11000,
    description: "Elegant and powerful sedan with a luxurious interior.",
    created_at: "10.06.2025",
    updated_at: "20.06.2025",
  },
  {
    id: 7,
    main_image: "/images/cars/audi-q7.jpg",
    name: "Audi Q7",
    version: "55 TFSI",
    rental_price: 2700,
    deposit_price: 10500,
    description: "Spacious and stylish SUV with advanced technology.",
    created_at: "15.06.2025",
    updated_at: "25.06.2025",
  },
  {
    id: 8,
    main_image: "/images/cars/porsche-911.jpg",
    name: "Porsche 911",
    version: "Carrera S",
    rental_price: 3500,
    deposit_price: 15000,
    description: "Iconic sports car with unmatched performance and handling.",
    created_at: "20.06.2025",
    updated_at: "30.06.2025",
  },
  {
    id: 9,
    main_image: "/images/cars/jaguar-f-type.jpg",
    name: "Jaguar F-Type",
    version: "R",
    rental_price: 3200,
    deposit_price: 14000,
    description:
      "Stunning sports car with a powerful engine and luxurious interior.",
    created_at: "25.06.2025",
    updated_at: "05.07.2025",
  },
  {
    id: 10,
    main_image: "/images/cars/land-rover-defender.jpg",
    name: "Land Rover Defender",
    version: "110",
    rental_price: 2900,
    deposit_price: 12000,
    description: "Rugged and versatile SUV with off-road capabilities.",
    created_at: "01.07.2025",
    updated_at: "10.07.2025",
  },
  {
    id: 11,
    main_image: "/images/cars/ferrari-488.jpg",
    name: "Ferrari 488",
    version: "GTB",
    rental_price: 4000,
    deposit_price: 20000,
    description: "Exotic sports car with breathtaking performance and design.",
    created_at: "05.07.2025",
    updated_at: "15.07.2025",
  },
  {
    id: 12,
    main_image: "/images/cars/lamborghini-huracan.jpg",
    name: "Lamborghini Huracan",
    version: "EVO",
    rental_price: 4500,
    deposit_price: 22000,
    description: "Aggressive and powerful supercar with stunning looks.",
    created_at: "10.07.2025",
    updated_at: "20.07.2025",
  },
  {
    id: 13,
    main_image: "/images/cars/rolls-royce-ghost.jpg",
    name: "Rolls-Royce Ghost",
    version: "Black Badge",
    rental_price: 5000,
    deposit_price: 25000,
    description:
      "Ultimate luxury sedan with unparalleled comfort and elegance.",
    created_at: "15.07.2025",
    updated_at: "25.07.2025",
  },
];
